export const expertise = [
	{ label: "Algorithm design", value: "AD" },
	{ label: "Algorithms", value: "ALGO" },
	{ label: "Artificial intelligence", value: "AI" },
	{ label: "Automata theory", value: "AUTO" },
	{ label: "Automated reasoning", value: "AR" },
	{ label: "Bioinformatics", value: "BIO" },
	{ label: "Coding theory", value: "CT" },
	{ label: "Compiler theory", value: "COM" },
	{ label: "Computability theory", value: "COMT" },
	{ label: "Computational chemistry", value: "COMC" },
	{ label: "Computational complexity theory", value: "COMCT" },
	{ label: "Computational physics", value: "COMP" },
	{ label: "Computational science", value: "COMS" },
	{ label: "Computer architecture", value: "COMA" },
	{ label: "Computer graphics", value: "CG" },
	{ label: "Computer programming", value: "CP" },
	{ label: "Computer security", value: "CS" },
	{ label: "Computer vision", value: "CV" },
	{ label: "Concurrency", value: "CON" },
	{ label: "Cryptography", value: "CRYP" },
	{ label: "Data mining", value: "DM" },
	{ label: "Data structures", value: "DS" },
	{ label: "Discrete Mathematics", value: "DMATH" },
	{ label: "Distributed computing", value: "DC" },
	{ label: "Evolutionary computing", value: "EC" },
	{ label: "Formal methods", value: "FM" },
	{ label: "Formal semantics", value: "FS" },
	{ label: "Game theory", value: "GAME" },
	{ label: "Graph theory", value: "GT" },
	{ label: "Human–computer interaction", value: "HCI" },
	{ label: "Image processing", value: "IP" },
	{ label: "Information visualization", value: "IV" },
	{ label: "Machine learning", value: "ML" },
	{ label: "Mathematical logic", value: "MATHLOGIC" },
	{ label: "Natural language processing", value: "NLP" },
	{ label: "Networking", value: "NET" },
	{ label: "Number theory", value: "NUM" },
	{ label: "Numerical analysis", value: "NA" },
	{ label: "Operating systems", value: "OS" },
	{ label: "Parallel computing", value: "PC" },
	{ label: "Programming language theory", value: "PLT" },
	{ label: "Quantum computing", value: "QC" },
	{ label: "Relational databases", value: "RD" },
	{ label: "Reverse engineering", value: "RE" },
	{ label: "Robotics", value: "ROB" },
	{ label: "Soft computing", value: "SC" },
	{ label: "Software engineering", value: "SWE" },
	{ label: "Structured Storage", value: "SS" },
	{ label: "Symbolic computation", value: "SYM" },
	{ label: "Type theory", value: "TT" },
];
